### PR TITLE
Fix #795 problems with hints

### LINKED ISSUE #795: rdbms_reader - problems with 'hints'
1. If I use an oracle optimizer hint in the select, the rdbms_reader tries to use the optimizer hint as an '[entity.]attribute' hint against the first column. This causes the component to produce wrong results, unless the first column happens to have its own 'entity.attribute' hint.
i.e.
SELECT /*+ ALL_ROWS */
    orders.order_id,
    orders.order_date,
....
will see "+ ALL_ROWS" as the '[entity.]attribute' hint for orders.order_id

2. If there is a wildcard in the select, hints on subsequent columns in the select statement are incorrectly applied to the numerically corresponding columns from the wildcarded table.
i.e
SELECT
    employees.*,
    departments.department_name /* departments.department_name */,
    departments.location_id /* departments.location_id */,
    departments.manager_id /* departments.dept_manager_id */
FROM
    employees
    left outer join departments on (employees.department_id=departments.department_id)

will apply the hints for the columns from the departments table to the 2nd, 3rd, and 4th columns of employees

### PR DESCRIPTION
**Pull request by kranskydog**
Allow column aliases for [entity.]attribute mapping
column aliases in format of attribute or "attribute" will be mapped to that attribute
column aliases in format of "entity.attribute" will be mapped to that entity.attribute
prevent Oracle optimizer hints being read as attribute hints
Signed-off-by: kranskydog <pjbrown@people.net.au>

### CODE REVIEW

**Comment by gwilmer** [comment]
kranskydog.  Thanks for your contributions to Metl.  We appreciate it!  I'm in the middle of some fairly major changes to the RDBMS Reader to allow it to deal with hierarchical models in addition to how it works today with relational models.  I'll go ahead and merge your code changes into what I have for this request instead of accepting the pull request if that's ok.  Should be easier for me to merge those changes in to what I have.  I should have it checked in by next week sometime.

Thanks again!

**Comment by kranskydog** [comment]
Hi.

NP. 

FWIW I think 'hints' should be deprecated in favour of column aliases.
1 - achieves exactly the same outcome
2 - column aliases are part of the sql and jdbc standard, and can be easily obtained from the resultset metadata, rather than having to parse the sql in code ( = less code in rdbms_reader)
3 - doesnt interfere with actual comments, optimizer hints etc in the sql statement

Just my 2c
Cheers, Phil

**Comment by gwilmer** [comment]
Phil,

I think the reason we originally went the hint route vs the alias route was because some database platforms that we were supporting didn't properly implement getColumnLabel.  I.E. the jdbc driver didn't return results for it, even though it should.  We support some off the beaten path database dialects.

I'm going to test your code with a bunch of different db dialects and make sure we are good.  We'll need to make sure we support hints for a while as many of our customers use them, but agreed, should be deprecated and eventually removed if all of the dialects work.

Thanks again for the contribution.

Greg W.

**Comment by kranskydog** [comment]
Hi Greg
Understood.
Cheers
Phil.

**Pull request closed without merging**
